Comment out 100-Continue expect header to hack image upload working again
On 4/24/2015, content creators reported that they could no longer upload images at /devadmin/content/items/new. The stack trace of the server error was:

```
S3ResponseError: 100 Continue
api/errors.py:76 in api_errors_formatted
api/auth/decorators.py:313 in wrapper
api/decorators.py:435 in jsonp_enabled
api/decorators.py:295 in wrapper
api/internal/assessment_items.py:941 in create_assessment_item_image
api/internal/assessment_items.py:923 in _upload_image_to_s3
third_party/boto/s3/key.py:1172 in set_contents_from_file
third_party/boto/s3/key.py:710 in send_file
third_party/boto/s3/key.py:882 in _send_file_internal
third_party/boto/s3/connection.py:543 in make_request
third_party/boto/connection.py:937 in make_request
third_party/boto/connection.py:837 in _mexe
third_party/boto/s3/key.py:839 in sender
```

Due to ancient mysteries of working with S3 uploads, boto decided to add this header even though it does not implement the full HTTP workflow that it implies. The full workflow was eventually added to the boto master branch (called botocore), but it has not been pushed into the boto package available for install, yet. Other people who have encountered this error state that commenting out this header relieves the issue, so that's what we're going to try.

Read more at these links.
Another reports the error and the workaround: https://github.com/boto/boto/issues/840
The "real" fix in botocore, that is not yet available in the install package: https://github.com/boto/botocore/commit/9e59c4e0e69ca6535dde35d839e6e5e65e03a5bb

Auditors: marcos

Test Plan:
Deploy to production, then:

1. Go to /devadmin/content/items/new
2. Click "Add Image"
3. Click "Choose files"
4. Select a file to upload
5. Click "Add Image"

You should not see a "Failed to upload image :(" error message.